- .github/workflows/account-deploy.yml
- .github/workflows/env-destroy.yml
- .github/workflows/env-test.yml
- .github/workflows/workflow-pr.yml
- Makefile
- docs/openapi/openapi.yaml
- lambda/create/main.go
- lambda/shared/problem.go
- mock-apigw/main.go
- signer/main.go
- terraform/account/.envrc
- terraform/account/.terraform.lock.hcl
- terraform/account/apigateway.tf
- terraform/account/terraform.tf
- terraform/account/terraform.tfvars.json
- terraform/account/variables.tf
- terraform/environment/outputs.tf
- terraform/environment/region/apigateway.tf
- terraform/environment/region/outputs.tf
- terraform/environment/region/variables.tf
- terraform/environment/regions.tf
- terraform/environment/terraform.tfvars.json
- terraform/environment/variables.tf
- terraform/modules/lambda/iam.tf
- terraform/modules/lambda/main.tf
- terraform/modules/lambda/outputs.tf
Use OpenAPI schema to define REST API, then add logging and IAM execution permissions.
Remove lambda function URLs. Test against REST API base URL.
Fixes VEGA-2014 #minor
> Add API Gateway

- .github/workflows/build-push-images.yml
- .github/workflows/env-test.yml
- .redocly.lint-ignore.yaml
- Makefile
- docker-compose.yml
- docs/openapi/openapi.yaml
- docs/schemas/lpa.json
- go.work
- go.work.sum
- lambda/Dockerfile
- lambda/get/go.mod
- lambda/get/go.sum
- lambda/get/main.go
- lambda/shared/client.go
- lambda/shared/ddb.go
- lambda/shared/go.mod
- lambda/shared/go.sum
- lambda/shared/lpa.go
- lambda/shared/update.go
- lambda/update/go.mod
- lambda/update/go.sum
- lambda/update/main.go
- mock-apigw/main.go
- signer/main.go
- terraform/environment/region/apigateway.tf
- terraform/environment/region/main.tf
- Add code for get and update lambdas
- Add OpenAPI spec
- Build lambda containers in CI
- Deploy lambdas for each endpoint
- Update tests to check each endpoint and assert final state
This includes adding `docs/schemas/lpa.json`, which can serve as a public JSON Schema definition _and_ get used in the OpenAPI doc.
For VEGA-2104 #minor
> Add baseline code for other API endpoints

- .github/workflows/generate-tag.yml
- .github/workflows/workflow-main.yml
Also splits out `generate-tag` into a reusable workflow rather than duplicating between the two workflows.
#minor
> Deploy to dev on merge to main

- .github/workflows/env-destroy.yml
- terraform/account/apigateway.tf
- terraform/account/region/dns.tf
- terraform/account/region/terraform.tf
- terraform/account/region/variables.tf
- terraform/account/regions.tf
- terraform/account/terraform.tf
- terraform/account/variables.tf
- terraform/environment/region/apigateway.tf
- terraform/environment/region/dns.tf
- terraform/environment/region/outputs.tf
- terraform/environment/region/variables.tf
- terraform/environment/regions.tf
Forward to API Gateway and use the DNS endpoint for tests
I've weighted 100% to eu-west-1 for now because multi-region signatures aren't well supported yet (i.e. you need to know which region you're signing for) and all our traffic originates in eu-west-1, but we should really take a proper look at this for future reliability.
#minor
> Add DNS records for environment

- .github/workflows/workflow-pr-close.yml
- docs/openapi/openapi.yaml
- go.work.sum
- terraform/environment/region/apigateway.tf
Move the health check to our [standard path](https://docs.opg.service.justice.gov.uk/documentation/adrs/adr-007.html) and remove authentication so it can be called from anywhere.
#minor
> Make healthcheck standard and available

- Makefile
- api-test/main.go
- docker-compose.yml
- lambda/create/main.go
- lambda/get/main.go
- lambda/shared/event.go
- lambda/shared/go.mod
- lambda/shared/go.sum
- lambda/shared/jwt.go
- lambda/shared/jwt_test.go
- lambda/shared/problem.go
- lambda/update/main.go
- terraform/environment/region/main.tf
This will parse an X-Jwt-Authorization header out of the incoming request and attempt to verify any JWT token value in it.
At the moment, we then log whether a token was verified, or reject the request with a 401 and log an error.
> VEGA-2105 Add JWT verification #minor

- docs/openapi/openapi.yaml
Expose the `updatedAt` field to provide an identifier of the version of the LPA you're looking at
#patch
> Add `updatedAt` to API schema

- .github/workflows/workflow-main.yml
- terraform/environment/terraform.tfvars.json
Operators shouldn't be able to call the API in non-development environments.
Also fix deployment to dev environment
#patch
> Require breakglass for preprod/prod access

- docs/openapi/openapi.yaml
Change openapi response mapping key to string, which was caught by the linter when referencing this from sirius
> Change openapi response mapping key to string

- docs/openapi/openapi.yaml
- internal/shared/problem.go
- lambda/get/main.go
Return 404 error when LPA is not retrieved VEGA-2203 #minor
> VEGA-2203 LPA Store returns 500 if it can't find an LPA

- .github/workflows/pact-provider-verification.yml
Using `--url` triggers additional (incorrect) pacts to be tested, `--webhook-callback-url` ensures that only the one specified is used.
#patch
> Use `--webhook-callback-url` when verifying pact

- .github/workflows/env-test.yml
- .github/workflows/workflow-pr.yml
- docker-compose.yml
- go.mod
- go.sum
- lambda/update/attorney_sign.go
- lambda/update/attorney_sign_test.go
- lambda/update/certificate_provider_sign.go
- lambda/update/certificate_provider_sign_test.go
- lambda/update/parse/changes.go
- lambda/update/parse/changes_test.go
- lambda/update/trust_corporation_sign.go
- lambda/update/trust_corporation_sign_test.go
- lambda/update/validate.go
Because I didn't like what I did in my previous PR...
> MLPAB-1639 Refactor changes by introducing a parser

- .github/workflows/pact-provider-verification.yml
`--url` unavoidably pulls in extra pacts
`--webhook-callback-url` doesn't exist on the published image
#patch
> Use consumer name and branch to specify Pact to test

- api-test/main.go
- docker-compose.yml
- terraform/environment/eventbridge.tf
- terraform/environment/region/iam.tf
- terraform/environment/region/lambda.tf
- terraform/environment/region/variables.tf
- terraform/environment/regions.tf
- terraform/environment/terraform.tfvars.json
- terraform/environment/variables.tf
- terraform/modules/eventbridge_cross_account_target/main.tf
- terraform/modules/eventbridge_cross_account_target/terraform.tf
- terraform/modules/eventbridge_cross_account_target/variables.tf
- terraform/modules/lambda/iam.tf
- terraform/modules/lambda/variables.tf
Includes:
- Event bus in LPA Store account
- Cross-account rule to send all locally-sourced events to the Sirius event bus
- Dead letter-queue to catch events that couldn't be sent
Fixes VEGA-2333 #minor
> Add EventBridge infrastructure

- .jira/config.yml
So that it can clearly display which environments have been deployed to.
#patch
> Add Jira deployment environment mapping

- docs/architecture/decisions/0002-actor-unique-ids.md
- docs/architecture/decisions/0003-cross-service-authorisation.md
Clarify how and when unique IDs for actors should be created.
Clarify the format of identifiers for cross-service authorisation.
#patch
> Add ADRs for unique actor IDs and authorisation

- terraform/modules/fixtures_service/security_group.tf
Since we're accessing the LPA Store API over the public web, and we can't determine its IP address, we need to allow public egress for the ECS container.
For VEGA-2424 #minor
> Give fixtures container global egress

- terraform/environment/region/apigateway.tf
- terraform/environment/region/variables.tf
- terraform/environment/regions.tf
- terraform/environment/terraform.tfvars.json
- terraform/environment/variables.tf
Introduces a new optional `allowed_wildcard_arns` environment property because wildcard ARNs need to be configured differently.
Will allow Sirius popup environments to work automatically.
Discovered during VEGA-2424 #minor
> Allow ephemeral Sirius environments to access dev

- internal/shared/lpa.go
- internal/shared/lpa_test.go
I think this is preferable to returning data to clients with both `lifeSustainingTreatmentOption` and `whenTheLpaCanBeUsed`, for example. I've extended it to all the (top-level) things that are optional, but are enforced by validation in create.
> MLPAB-1223 Omit fields that are optional from LpaInit

- docker-compose.yml
- fixtures/app.py
- fixtures/static/js/json-schema-editor.mjs
- fixtures/static/js/jsonpointer.mjs
- fixtures/static/js/main.mjs
- fixtures/static/json/lpa-schema.json
- fixtures/templates/index.html
Use the JSON schema to generate a bunch of nested fields so that users don't need to understand JSON in order to create fixture data in the store.
For now I've hard-coded the current JSON schema for ease, but I'm hoping to work on formalising all the schemas properly soon.
Fixes CTC-145 #minor
> Add visual editor to fixtures

- .github/workflows/env-destroy.yml
Need to have OpenAPI file in order to run `terraform destroy`.
This has left a few environments undestroyed, so I'll come back to make this workflow dispatchable by environment name
#patch
> Fix environment destruction

- api-test/main.go
- internal/shared/jwt.go
- internal/shared/jwt_test.go
We no longer need to support email address sub values for validation in the LPA store.
Update [jwt.go](https://github.com/ministryofjustice/opg-data-lpa-store/blob/d23d519270bff83961ad59e12f2d87d5f8e8dbe9/internal/shared/jwt.go) to remove email address validation for sub fields.
[vega-2342](https://opgtransform.atlassian.net/browse/VEGA-2343)
> vega-2343 - Remove email validation in jwt sub

- Makefile
- docs/certificate-provider-change.json
- docs/example-lpa.json
- lambda/update/certificate_provider_sign.go
- lambda/update/certificate_provider_sign_test.go
- lambda/update/parse/changes.go
- lambda/update/parse/changes_test.go
Confirmed this is working now we match the hardcoded API Gateway mock values for an existing LPA:
We'll go through this for attorneys and trust corps next and then drop the `MustMatchExisting` opt.
I think longer term it would be useful to either define what some existing values in the LPA are as part of the test (e.g. `An LPA exists with UID XXX and Address 1 fake road, town, postcode etc`) or pull in the existing values from a central repository as its unclear from the consumer side what existing values need to be provided and where they are defined
Fixes MLPAB-1546
> MLPAB-1546: Enforce matching old and existing for CERTIFICATE_PROVIDER_SIGN

- docs/architecture/decisions/0004-use-json-schemas-to-define-lpa-structure.md
- docs/openapi/openapi-aws.override.yaml
- docs/openapi/openapi.yaml
- docs/schemas/2024-04/donor-details.json
- docs/schemas/2024-04/lpa.json
- docs/schemas/2024-04/submitted-lpa.json
- docs/schemas/2024-04/translation.cy.json
- docs/schemas/2024-04/translation.en.json
`lpa.json` is now the full LPA structure. `submitted-lpa.json` is the subset of fields that should initially be initially submitted from MRLPA or scanning.
Create `translation.*.json` to indicated what translation files might look like/contain.
Add an ADR documenting how we will use, host and version our JSON schemas.
#minor
> Cleanup JSON schemas and add ADR

- lambda/create/validate.go
- lambda/create/validate_test.go
Partially fixes [MLPAB-2088](https://opgtransform.atlassian.net/browse/MLPAB-2088). As part of the MRLPA work we will be making email an optional field for trust corps so we can infer the channel.
I'll come back and uncomment the validation for channel + email once consumer tests are updated.
> MLPAB-2088: Make email optional, channel required for create trust corporation

- lambda/create/validate_test.go
As we relied on `assert.Contains()` in our validation tests could add and remove validations not explicitly tested for in tests and have them pass. Being more specific in our assertions using `assert.Equals()` and `assert.ElementsMatch()` should give us more confidence in our unit tests when making changes to validation.
> Use equality checks rather than contains in validation tests

- Makefile
- docs/certificate-provider-opt-out.json
- docs/openapi/openapi.yaml
- internal/shared/lpa.go
- lambda/update/certificate_provider_opt_out.go
- lambda/update/certificate_provider_opt_out_test.go
- lambda/update/validate.go
Partially fixes [MLPAB-1269](https://opgtransform.atlassian.net/browse/MLPAB-1269). 
[MLPAB-1269]: https://opgtransform.atlassian.net/browse/MLPAB-1269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MLPAB-1269: Support CERTIFICATE_PROVIDER_OPT_OUT update

- fixtures/static/js/json-schema-editor.mjs
- internal/shared/date.go
- internal/shared/date_test.go
- lambda/create/main.go
We can't kick back a 400 response to the scanners because they can't change what they send, so log and accept the validation errors.
Plus fix an existing bug with unmarshalling empty dates.
For CTC-146 #patch
> Don't enforce validation on paper-channel LPAs

- docs/schemas/2024-10/donor-details.json
- fixtures/static/js/json-schema-editor.mjs
- internal/objectstore/client.go
- internal/objectstore/client_test.go
- internal/shared/image.go
- internal/shared/lpa.go
- lambda/create/main.go
- Alter schema to change fields available based on form channel
- Add `FileUpload` and `File` struct types
- `FileUpload` is used in submissions, `File` is used to pass back
- Add `S3Client.UploadFile` to copy base64-encoded files into S3
- On submission of Paper LPAs, store `FileUpload` objects in S3 and return a reference to them in `File`
- Update the fixtures UI to support uploads
For CTC-146 #minor
> Support image-based R&C for Paper LPAs

- fixtures/requirements.txt
This fixes a dependabot security issue.
I ended up doing this manually due to an inexplicable error coming from the PR generated by dependabot.
> Upgrade requests to 2.32.0 (fixes dependabot security issue)

- internal/objectstore/client.go
- lambda/create/main.go
- lambda/get/main.go
- lambda/getlist/main.go
- lambda/update/main.go
V1 endpoint resovlers are being deprecated, so instead set a BaseEndpoint in config and use path style URLs.
#patch
> Migrate AWS endpoint configuration

- CODEOWNERS
It's a shared repo so both teams should be owners (though in reality most people are in both teams anyway).
#patch
> Add opg-modernising-lpa-team to CODEOWNERS

- docs/certificate-provider-confirm-identity.json
- docs/donor-confirm-identity.json
- docs/schemas/2024-10/donor-details.json
- internal/shared/person.go
- internal/validate/validate.go
- lambda/create/validate.go
- lambda/create/validate_test.go
- lambda/update/confirm_identity.go
- lambda/update/confirm_identity_test.go
To avoid having modernise filled with 
```
SendLpa(...)
SendDonorConfirmIdentity(...)
```
> MLPAB-2044 Add validation for donor identity check with initial LPA

- terraform/account/data_sources.tf
- terraform/account/secrets.tf
This secret value needs to be accessed by MLPA and UaL. In this PR, I will create a new secret to hold a copy of the secret.
Fixes MLPAB-2189
- Create a secret called `opg-data-lpa-store/<account-name>/jwt-key` in the management account
- Configure replication for the secret to eu-west-2
- Use data sources for tags and region to make refactoring easier
> Create a replicated secret in management account for the jwt-key

- docs/schemas/2024-10/donor-details.json
Rather than saying it must be `#/$defs/IdentityCheck` and an object, just require it to be `#/$defs/IdentityCheck`.
This also fixes the fixtures editor JS.
#patch
> Simplify identity check schema

- docker-compose.yml
- internal/shared/jwt.go
- terraform/environment/region/data_sources.tf
- terraform/environment/region/iam.tf
- terraform/environment/region/lambda.tf
- terraform/environment/region/terraform.tf
- terraform/environment/region/variables.tf
- terraform/modules/lambda/iam.tf
Migrate toward using a shared secret for the JWT Key, making it easier for other services to access the key.
- refactor iam policies, so general actions (logging) are in module and purpose specific (accessing secrets, dynamodb access) are outside
- fix linter findings
- rename environment variable to `JWT_SECRET_KEY_ARN`
- https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/secretsmanager#GetSecretValueInput
- https://docs.aws.amazon.com/secretsmanager/latest/userguide/auth-and-access_examples.html#auth-and-access_examples_read
> MLPAB-2237 - Refactor IAM policies ahead of move to shared secret usage

- terraform/account/kms_key_jwt_secret.tf
- terraform/account/secrets.tf
- terraform/account/terraform.tfvars.json
Previous change resulted in an error for an invalid kms policy. Removing secret encryption and secret policy to unblock path to live while I resolve the issue
- Remove policy and kms id from secret
- fix reference to event-received preproduction
- remove reference to root access (though this with conditions may be the solution)
> MLPAB-2237 - remove policy and encryption

- terraform/account/kms_key_jwt_secret.tf
- terraform/account/secrets.tf
- terraform/account/terraform.tfvars.json
- terraform/account/variables.tf
- terraform/environment/region/data_sources.tf
- terraform/environment/region/iam.tf
- terraform/modules/lambda/iam.tf
Make the JWT secret accessible by external account roles.
- Grant external account access to KMS key, and use conditions to restrict to specific roles
- Grant external account access to secret, using the same conditions
- Use CMK for secret encryption
- Move lambda IAM roles to path to make use in IAM policy documents easier
- Allow lambda to decrypt secret
- https://docs.aws.amazon.com/kms/latest/developerguide/key-policy-modifying-external-accounts.html
- https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html
> MLPAB-2237 Allow KMS key and secret to be used across accouts

- .github/workflows/account-deploy.yml
- .github/workflows/env-deploy.yml
output a plan and apply it, this will save on refreshing state a second time necessarily.
- output a plan
- apply the outputted plan
- remove capturing plan output for PR comment summaries as they weren't being used and take up time
- https://developer.hashicorp.com/terraform/cli/commands/plan
> apply plan output

- terraform/account/region/secrets.tf
- terraform/account/region/variables.tf
- terraform/account/regions.tf
Now that lpa store and other services can use the shared key, we can remove the old one
- remove old secret (the one local to the service)
- remove unused variable
NOTE: Sirius and MLPAB needs to be using the shared secret before this is merged!
> MLPAB-2237 - remove old secret

- fixtures/static/js/json-schema-editor.mjs
Due to a some browser/rendering weirdness, when <select>s are added to the page their initial value is `""` but they're shown as having the first non-empty value selected.
Use `requestAnimationFrame` to force the value to be `""` immediately. rAF is necessary to let the browser's initial state settle first.
> Force the initial value of selects to be "" #patch

- terraform/environment/region/fixtures.tf
- terraform/modules/fixtures_service/data_sources.tf
- terraform/modules/fixtures_service/iam.tf
- terraform/modules/fixtures_service/secrets.tf
- terraform/modules/fixtures_service/variables.tf
Migrate to the new shared secret for jwt for fixtures app
- allow fixtures iam role to access secret and and kms key
- remove old secret
> MLPAB-2237 - use new secret in fixtures

- fixtures/static/js/json-schema-editor.mjs
Currently the values shown on screen are auto-filled based on the schema. This includes selecting the first value of enum dropdowns. But the data saved in the textarea (which is ultimately sent to the API) doesn't have these which can cause confusion.
#patch 
To ensure alignment, after filling in default values save the new data back to the textarea so that it represents what's actually being displayed.
This makes the textarea slightly harder to edit manually, but no-one's doing that anyway.
This replaces the `requestAnimationFrame` fix which just caused different issues.
> Fix default values in fixtures app

- fixtures/static/js/json-schema-editor.mjs
When unpopulated donor.identityCheck and certificateProvider.identityCheck are being sent with blank values. This causes an Unmarshalling error in the API. To allow creation of test data for a demo of paper ID these are temporarily being removed from the fixture form.
> Remove identityCheck from the fixture form #patch

- .github/workflows/build-push-images.yml
To avoid getting caught by rate limiting on the public resource.
#patch
Copied from [Paper ID](https://github.com/ministryofjustice/opg-paper-identity/pull/258)
> Use ECR-hosted Trivy DB rather than public image

- fixtures/static/js/json-schema-editor.mjs
json-schema-library is defaulting al text fields to empty strings. This is fine for general text fields, but causes problems for dates as the the API then tries to unmarshal the string and finds it isn't a valid ISO-8601 date.
Empty date strings should instead be treated as `null` so that unmarshaling is skipped.
Fixes VEGA-2708 #patch
When writing default values into the JSON object, specifically convert empty-string date fields to null.
This awkwardness was caused because other fields need to be defaulted to a valid value in order to show in the UI properly. In the future, replacing this with a properly designed form and/or scanning will give us much better control over default values.
> Default date fields to null

- docker-compose.yml
- docs/opg-status-change.json
- internal/shared/lpa.go
- lambda/update/opg_change_status.go
- lambda/update/opg_change_status_test.go
- lambda/update/parse/changes.go
- lambda/update/validate.go
This covers [VEGA-2501](https://opgtransform.atlassian.net/browse/VEGA-2501)
The changes add a new validation / application file for changing the status manually. Currently, the implementation only allows the status change to 'Cannot register'. This can / will be extended / modified to include other statuses as new requirements come along. It will just need additions / amendments to the logic inside **opg_status_change.go**
[VEGA-2501]: https://opgtransform.atlassian.net/browse/VEGA-2501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VEGA-2501 : Manual Status Change #minor

- .github/workflows/pact-provider-verification.yml
- Makefile
- api-test/main.go
- docker-compose.yml
- internal/shared/jwt_test.go
- localstack/init/localstack_init.sh
This PR updates the JWT secret across the LPA Store so that it matches the JWT secret being sent from Sirius thereby allowing a local setup between both without any manual updates to the JWT secret key.
Everywhere where the old JWT secret is being used has been replaced with the new one.
There is a file - opg-data-lpa-store/terraform/account/kms_key_jwt_secret.tf. I am unsure about whether a change is needed in the section below in BOLD or whether its just a description text -
```
module "jwt_kms" {
source                  = "../modules/kms_key"
**encrypted_resource      = "jwt key secret"**
kms_key_alias_name      = "${data.aws_default_tags.default.tags.application}/${data.aws_default_tags.default.tags.account}/jwt-key"
enable_key_rotation     = true
enable_multi_region     = true …
```
> Update the JWT secret and change the port on fixtures service #patch

- lambda/update/opg_change_status.go
- lambda/update/opg_change_status_test.go
This PR covers [VEGA-2500](https://opgtransform.atlassian.net/browse/VEGA-2500)
The PR change adds new rules to the OPG_STATUS_CHANGE change type to include the manual case status update to the 'Cancelled' status. The tests have been updated.
The logic checks the old values and new values to ensure that they conform to the business rules for changing the status manually to 'Cancelled' and also ensures that the existing logic around the manual case status update to 'Cannot Register' still continues to work.
[VEGA-2500]: https://opgtransform.atlassian.net/browse/VEGA-2500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VEGA-2500 : Handle manual change to cancelled status #minor

- internal/shared/lpa.go
- lambda/update/opg_change_status.go
- lambda/update/opg_change_status_test.go
This PR covers [VEGA-2638](https://opgtransform.atlassian.net/browse/VEGA-2638)
The existing validations have been updated and new one added to implement the status change for 'Do Not Register'. The tests have been updated.
[VEGA-2638]: https://opgtransform.atlassian.net/browse/VEGA-2638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VEGA-2638 : Handle Do Not Register status update  #minor

- internal/shared/lpa.go
- lambda/update/opg_change_status.go
- lambda/update/opg_change_status_test.go
This PR covers [VEGA-2661](https://opgtransform.atlassian.net/browse/VEGA-2661) allowing the change of Lpa status to Expired while the status is In Progress, Statutory Waiting Period or Do not register.
[VEGA-2661]: https://opgtransform.atlassian.net/browse/VEGA-2661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VEGA-2661 : Handle manual update of Expired status #minor

- docs/correction.json
- lambda/update/correction.go
- lambda/update/correction_test.go
- lambda/update/parse/changes.go
- lambda/update/parse/changes_test.go
- lambda/update/validate.go
This PR includes lpa-store changes to allow a Sirius user to change donor details via a Correction
Fixes ([VEGA-2667](https://opgtransform.atlassian.net/jira/software/projects/VEGA/boards/170))
This follows the same pattern used for the update lambdas. It also adds a check for a Date object for dates of births in oldEqualsExisting().
[VEGA-2667]: https://opgtransform.atlassian.net/browse/VEGA-2667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VEGA-2667 correction when changing donor details

- docs/example-lpa.json
- docs/schemas/2024-10/lpa.json
- internal/shared/person.go
- lambda/create/main_test.go
- lambda/create/validate.go
- lambda/create/validate_test.go
- mock-apigw/main.go
Ticket to split the attorney status into two fields, the status and the appointment type (original and replacement)
Fixes (VEGA-2656)
> Vega 2656 add appointment type and new status

- terraform/environment/terraform.tfvars.json
The "default" environment configuration is used by pop-up environments. It should not have a target event bus because there's no valid bus to send to.
The existing config (sending to the Sirius dev event bus) is invalid because Sirius can't then read the LPA back from the store: it tries—and fails—to use the dev LPA Store, not the pop-up.
Fixes VEGA-2790 #patch
Removed target event bus from config
> Remove target event bus from default env config

- docs/schemas/2024-10/donor-details.json
Rather than having one or the other, always allow `restrictionsAndConditions` and only allow `restrictionsAndConditionsImages` if it's a paper LPA.
This is necessary because severances will cause images on a paper LPA to be replaced by text instead.
#minor
> Update logic for Restrictions and Conditions/images

- lambda/update/correction.go
- lambda/update/correction_test.go
Updates the correction event to allow for attorney details to also be corrected
Fixes (VEGA-2743)
Implementation just adds to the current correction method
> VEGA-2743 allow attorney details correction

- lambda/update/correction.go
- lambda/update/correction_test.go
[VEGA-2793](https://opgtransform.atlassian.net/browse/VEGA-2793?atlOrigin=eyJpIjoiODhjYTAwZjI3Zjk4NGMzMGIwNzllN2MzNDIwYTZhZGYiLCJwIjoiaiJ9) Adds support for Certificate Provider corrections.
Updated `corrections.go`, similar to how we update the donor and attorneys.
n/a
[VEGA-2793]: https://opgtransform.atlassian.net/browse/VEGA-2793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VEGA-2793 Change Certificate Provider details

- docs/schemas/2024-10/donor-details.json
- docs/schemas/2024-10/lpa.json
- internal/shared/person.go
- lambda/create/validate.go
- lambda/create/validate_test.go
- lambda/update/attorney_opt_out_test.go
- lambda/update/trust_corporation_opt_out_test.go
[VEGA-2658](https://opgtransform.atlassian.net/browse/VEGA-2658?atlOrigin=eyJpIjoiMzc5MThmYjdiMDE0NGUwNDk3ODk2OTQ0YzFkNzRhMTMiLCJwIjoiaiJ9) Update count attorneys func to return active attorneys and inactive replacement attorneys. Fix tests and refactor status tests.
Remove the `replacement` attorney status.
Active attorneys are now either active original attorneys or active replacement attorneys. The old concept of replacement attorneys are now inactive replacement attorneys.
n/a
[VEGA-2658]: https://opgtransform.atlassian.net/browse/VEGA-2658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VEGA-2658 Remove replacement attorney status, add inactive status to schemas

- internal/validate/validate.go
- internal/validate/validate_test.go
- internal/validate/validators.go
- internal/validate/validators_test.go
- lambda/create/validate.go
- lambda/update/attorney_opt_out.go
- lambda/update/attorney_sign.go
- lambda/update/certificate_provider_sign.go
- lambda/update/confirm_identity.go
- lambda/update/correction.go
- lambda/update/opg_change_status.go
- lambda/update/parse/changes.go
- lambda/update/parse/changes_test.go
- lambda/update/trust_corporation_opt_out.go
- lambda/update/trust_corporation_sign.go
Pros:
- less repetition when used with `update/parse`
Cons:
- have to deal with `type` and `*type` in the validators
> Refactor validation so it works better for both use cases

- docs/change-attorneys.json
- lambda/update/change_attorneys.go
- lambda/update/change_attorneys_test.go
- lambda/update/parse/changes.go
- lambda/update/validate.go
This PR covers [VEGA-2822](https://opgtransform.atlassian.net/browse/VEGA-2822)
The changes add a new validation / application file for changing the attorney status manually. The implementation only allows the status changes to multiple attorneys at the same time. This will cover both the removal of an attorney as well as enabling a replacement attorney.
[VEGA-2822]: https://opgtransform.atlassian.net/browse/VEGA-2822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VEGA-2822 : Implementation of attorney status change functionality

- .sonarcloud.properties
It's very rarely helpful and constantly throws false positives
> Turn off SonarCloud duplicate code detection

- lambda/update/statutory_waiting_period.go
- lambda/update/statutory_waiting_period_test.go
Only active and replacement attorneys need to have signed the LPA for it to be registered.
Fixes VEGA-2896 #minor
Tweaked logic, added test
> Do not require signatures from inactive attorneys

- fixtures/Dockerfile
- fixtures/app.py
- fixtures/lib/api.py
- fixtures/package-lock.json
- fixtures/package.json
- fixtures/templates/form_signature.html
- fixtures/templates/index.html
- fixtures/templates/layout.html
- fixtures/templates/partials/error_summary.html
Add new endpoints where users can emulate an attorney of CP signing a paper form.
This will allow basic end-to-end testing of paper participants, letting Sirius test later stages of the process and providing more testing options.
Fixes VEGA-2807 #patch
Added new endpoint handlers and templates.
I tidied up the existing HTML to add a reusable layout, and added an `api` library file to help with some of the repetitive bits.
I added `@ministryofjustice/frontend` for the date picker.
N/A
> Add attorney/CP sign forms to fixtures

- api_test.go
- docs/example-lpa.json
- docs/sever-restrictions-and-conditions.json
- lambda/update/sever_restrictions.go
- lambda/update/sever_restrictions_test.go
- lambda/update/validate.go
Ticket to add SEVER_RESTRICTIONS_AND_CONDITIONS update change type, to allow changes to restrictions and conditions. This can in rare circumstances occur after registration. 
Fixes (VEGA-2917)
Follows previously established patterns.
> VEGA-2917 add sever restrictions and conditions to store

- terraform/account/opg_metrics.tf
- terraform/account/terraform.tf
- terraform/account/terraform.tfvars.json
- terraform/account/variables.tf
Add an Eventbridge API destination for opg-metrics
Fixes MLPAB-2905
NOTE: OPG metrics only currently exists in the shared-dev account, and only in the eu-west-1 region. All environments will point to this endpoint until production environments and dual region deployment is sorted for opg-metrics.
- add shared account providers
- create api destination
> Create an API destination for opg-metrics

- .github/workflows/schedule-update-opg-metrics-credentials.yml
OPG Metrics rotates credentials on a daily basis. Lambda functions using OPG Metrics directly fetch API keys, but Event Bridge API destinations store a copy of the credentials. 
Fixes MLPAB-2991
- Schedule a job after the API key rotation (2am) to update the stored credential
- https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
- https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow
> MLPAB-2991 - add scheduled job to update api key for opg metrics

- terraform/environment/region/iam.tf
So that it can generate pre-signed URLs for images
Fixes VEGA-2984 #patch
> Allow lambda role to GetObject from S3

- lambda/update/parse/changes.go
Iterating a hashmap makes some tests flakey.
Fixes CTC-205 #patch
Iterating over a map causes the order to be unreliable, because hashmaps don't have order. This some error messages non-idempotent, which results in flakey tests.
Keep track of the order of the changes and process the groups based on which prefix had a value listed first.
I didn't know you could do `-run {regex}` to only run particular tests with `go test`. That made recreating the bug and confirming the fix much easier.
> Don't lose order when grouping changes by key

- lambda/create/main.go
- lambda/create/main_test.go
If any actors have not been assigned a UID when the case is created, automatically add one.
This ensures they will have a consistent identity for all future events and interactions.
Fixes VEGA-2988 #minor
> Ensure actors have UIDs on creation

- .github/workflows/generate-tag.yml
- terraform/account/terraform.tfvars.json
- terraform/environment/terraform.tfvars.json
And remove the finance roles from preprod allowed ARNs as they don't exist any more
Fixes SP-2875 #patch
> Replace `anothrNick/github-tag-action` with `ministryofjustice/opg-github-actions/.github/actions/semver-tag`

- lambda/update/opg_change_status.go
- lambda/update/opg_change_status_test.go
This PR is for [VEGA-2977](https://opgtransform.atlassian.net/browse/VEGA-2977). As part of this PR, the error message for manual status update has been made more generic to cater to statuses like Do Not Register which needs to be updated by the `opg_change_status.go` file but cannot be updated manually.
The PR changes the error message to a more generic one.
[VEGA-2977]: https://opgtransform.atlassian.net/browse/VEGA-2977?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VEGA-2977 : Disable Do Not Register manual update #minor

- internal/shared/lpa.go
- lambda/update/change_attorneys.go
- lambda/update/change_attorneys_test.go
Add a Note to the LPA when an attorney is removed.
Fixes [VEGA-2935](https://opgtransform.atlassian.net/browse/VEGA-2935)
Add a map to the LPA struct for the notes and a method to add a note. Call this when attorneys are being removed.
n/a
[VEGA-2935]: https://opgtransform.atlassian.net/browse/VEGA-2935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VEGA-2935 Add Note when attorney removed

- lambda/update/change_attorneys_test.go
- lambda/update/sever_restrictions.go
- lambda/update/sever_restrictions_test.go
Adds a Note when restrictions and conditions are severed.
Fixes [VEGA-2915](https://opgtransform.atlassian.net/browse/VEGA-2915)
Uses LPA `AddNote` method.
Use `Object.(type)` to type check an interface and get its value.
[VEGA-2915]: https://opgtransform.atlassian.net/browse/VEGA-2915?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VEGA-2915 Add note for restrictions and conditions severance

- internal/shared/lpa.go
- lambda/update/change_attorneys.go
- lambda/update/change_attorneys_test.go
- lambda/update/correction.go
- lambda/update/correction_test.go
- lambda/update/sever_restrictions.go
- lambda/update/sever_restrictions_test.go
Adds a note for when the certificateProvider changes either first or surname
Fixes [vega-2938](https://opgtransform.atlassian.net/browse/VEGA-2938)
Explain how your code addresses the purpose of the change
> VEGA-2938 Add note for certificateProvider name change

- lambda/update/correction.go
- lambda/update/correction_test.go
This PR covers [VEGA-2937](https://opgtransform.atlassian.net/browse/VEGA-2937) which adds a static note to the LPA when the donor's name is changed.
Explain how your code addresses the purpose of the change
[VEGA-2937]: https://opgtransform.atlassian.net/browse/VEGA-2937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VEGA-2937 : Add a static note when donor's name is updated #minor

- lambda/update/correction.go
- lambda/update/correction_test.go
PR to prevent the donor's date of birth to be changed once the identity check has been made on the donor.
Fixes (VEGA-2751)
Returns FieldError if a donor date of birth change is being made and the identity check checked at field has already been set.
> VEGA-2751 do not allow donor dob change after identity check

- lambda/update/post_registration_correction.go
- lambda/update/post_registration_correction_test.go
- lambda/update/validate.go
This PR covers [VEGA-3212](https://opgtransform.atlassian.net/browse/VEGA-3212)
As part of this PR, a new change type has been added to accommodate post registration corrections for a signed LPA. At the moment, just the change type has been added with a new class for it and there is no logic or tests around it. There are tickets after this which will incorporate logic into the corrections and at that time, there will be more exhaustive tests to cover the implementation for all the relevant actors of the LPA.
[VEGA-3212]: https://opgtransform.atlassian.net/browse/VEGA-3212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VEGA-3212 : Add a new change type for post registration corrections

- mock-apigw/main.go
[VEGA-3107](https://opgtransform.atlassian.net/browse/VEGA-3107)
Fixes (Ticket Reference)
Added the correct mocked endpoint changes for local dev
[VEGA-3107]: https://opgtransform.atlassian.net/browse/VEGA-3107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VEGA-3107: added route for mocking/fetching changes/updates
