lambda/Dockerfile

To avoid a vulnerability reported by Trivy
#patch

Upgrade libcrypto

---

README.md
docs/architecture/dsl/local/lpaStore.dsl
docs/architecture/dsl/local/workspace.dsl
docs/openapi/openapi.yaml
lambda/create/go.mod
lambda/create/main.go
lambda/get/go.mod
lambda/get/main.go
lambda/shared/go.mod
lambda/shared/problem.go
lambda/update/go.mod
lambda/update/main.go
mock-apigw/go.mod
renovate.json
signer/go.mod
terraform/account/variables.tf
terraform/environment/variables.tf

Update go modules, AWS tagging and Renovate config.
Also update the name in the README, structurizr docs and OpenAPI spec
#major

Rename "opg-data-lpa-deed" to "opg-data-lpa-store"

---

.github/workflows/pact-provider-verification.yml
api-test/main.go
docker-compose.yml
mock-apigw/main.go

Add a pipeline that runs on PRs, branches and on repository dispatch.
Requires a JWT to be generated beforehand and included in headers for authentication.
Fixes VEGA-2196 #minor

Add Pact provider tests

---

terraform/environment/terraform.tfvars.json

Will add preprod and prod when those environments exist

MLPAB-1637 Add allowed arns for modernising to call

---

.github/workflows/account-deploy.yml
.github/workflows/workflow-main.yml
.github/workflows/workflow-pr.yml
terraform/account/terraform.tfvars.json

Plan the account deployments in PR pipelines, and run in main build.
Fixes CTC-129 #major

Deploy to preproduction and production accounts

---

.github/workflows/env-deploy.yml
.github/workflows/workflow-main.yml
.github/workflows/workflow-pr.yml
terraform/environment/terraform.tfvars.json

Test deployments in the PR workflow, then deploy them in the main workflow.
Includes access for related environments in MRLPA
#major

Deploy preprod, prod and demo environments

---

docs/openapi/openapi.yaml

additionalProperties need to be set to false

Add additionalProperties false to openapi spec

---

docs/openapi/openapi.yaml
internal/shared/lpa.go
internal/shared/person.go
lambda/create/validate.go
lambda/create/validate_test.go
mock-apigw/main.go

Relates to https://github.com/ministryofjustice/opg-modernising-lpa/pull/926

MLPAB-1637 Add more data to the LPA

---

.github/workflows/pact-provider-verification.yml

See https://github.com/ministryofjustice/opg-data-lpa-store/actions/runs/7669241900/job/20902738184
```
error: unexpected argument '--webhook-callback-url' found
```

Remove unexpected --webhook-callback-url argument from pact verification 

---

.github/workflows/pact-provider-verification.yml

Remove unnecessary backslash escapes

Fix escaping in Pact verifier command

---

Makefile
api-test/main.go
docker-compose.yml
localstack/init/localstack_init.sh
localstack/wait/healthcheck.sh

No point having extra containers, localstack is familiar and natively supports initialisation and healthchecks.
For VEGA-2333 #patch

Move DynamoDB into localstack

---

internal/event/client_test.go
lambda/create/main.go
lambda/update/main.go
lambda/update/main_test.go

Fixes [MLPAB-1544](https://opgtransform.atlassian.net/browse/MLPAB-1544)
[MLPAB-1544]: https://opgtransform.atlassian.net/browse/MLPAB-1544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MLPAB-1544: Update change types

---

terraform/account/region/terraform.tf
terraform/account/region/vpc.tf

So that Lambda and ECS inside the VPC can connect to AWS services
For CTC-140 #minor

Create VPC endpoints + security group

---

terraform/account/region/vpc.tf
terraform/environment/region/data_sources.tf
terraform/environment/region/lambda.tf
terraform/environment/region/variables.tf
terraform/environment/regions.tf
terraform/modules/lambda/main.tf
terraform/modules/lambda/security_group.tf
terraform/modules/lambda/variables.tf

Includes adding a security group for VPC endpoint connection
For CTC-140 #minor

Move Lambda inside VPC

---

terraform/account/region/secrets.tf
terraform/account/region/variables.tf
terraform/account/regions.tf

So it can be pulled into lambdas and ECS
For VEGA-2424 #minor

Add JWT signing key secret

---

terraform/account/region/secrets.tf

If I had a nickel for every time...
For VEGA-2424 #patch

Use correct provider on JWT key secret

---

.github/workflows/env-destroy.yml
.github/workflows/workflow-pr-close.yml

So that it can initialise properly and destroy the temporary env
#patch

Pass allowlist deploy key to destroy workflow

---

terraform/environment/terraform.tfvars.json

Add IAM access for Sirius API execution role

---

Makefile
api-test/main.go
docs/example-lpa.json
internal/shared/date.go
internal/shared/date_test.go
internal/shared/lpa.go
internal/shared/lpa_test.go
internal/shared/person.go
internal/validate/validate_test.go
lambda/create/validate_test.go
lambda/update/attorney_sign.go
lambda/update/attorney_sign_test.go
lambda/update/certificate_provider_sign.go
lambda/update/certificate_provider_sign_test.go
lambda/update/main_test.go

This also adds a test to check that the GET matches what was PUT (ignoring a few keys which won't), this has meant making a few more things `,omitempty` and fixing the `Date` serialisation

MLPAB-2048 Store actor uids and omit other empty fields

---

terraform/environment/terraform.tfvars.json

Add access to LPA Store from Sirius preprod and prod ECS execution roles
#minor

Give preprod/prod Sirius roles access

---

.github/workflows/workflow-env-destroy.yml

Can't depend on a job that doesn't exist 🙃
#patch

Remove typo

---

docs/openapi/openapi.yaml
lambda/update/register.go
lambda/update/register_test.go
lambda/update/validate.go

I know this may seem a bit early, but I'm trying to remove the special cases we currently have in modernise with fake data that won't exist in the future. And we know we'll need _something_ like this, even if it may end up being slightly different.

MLPAB-2035 Add REGISTER update type

---

docker-compose.yml
fixtures/Dockerfile
fixtures/lib/jwt.py

- Mount schema properly
- Use appropriate JWT sub

Fix issues with fixtures container

---

docs/schemas/2024-04/donor-details.json
internal/shared/lpa_test.go
internal/shared/person.go
internal/validate/validate.go
internal/validate/validate_test.go
lambda/create/validate_test.go

[vega-2431](https://opgtransform.atlassian.net/browse/VEGA-2431)

vega-2431 - Remove 'town' as required field in address

---

docs/example-lpa.json
docs/schemas/2024-10/donor-details.json
fixtures/templates/index.html
internal/shared/lpa.go
internal/shared/lpa_test.go
lambda/create/validate.go
lambda/create/validate_test.go
mock-apigw/main.go

To be used in future validation: if the LPA comes through the paper channel then validation wll be more lenient
Originally part of MLPAB-1535 #minor

Add `channel` field to LPA

---

docs/openapi/openapi.yaml
docs/schemas/2024-10/lpa.json

To better support mock generators (e.g. [Imposter](https://github.com/outofcoffee/imposter))

Update schema $refs to data-dictionary

---

docs/schemas/2024-10/donor-details.json

Same as #225 but for certificate provider
#patch

Simplify CP identity check schema

---

docs/schemas/2024-10/lpa.json
internal/shared/lpa.go
lambda/create/main.go
lambda/update/certificate_provider_opt_out_test.go
lambda/update/perfect.go
lambda/update/perfect_test.go
lambda/update/register_test.go

[vega-2552](https://opgtransform.atlassian.net/browse/VEGA-2552)

vega-2552 - Change 'processing' status to 'in-progress'

---

docs/openapi/openapi.yaml
docs/schemas/2024-10/lpa.json
internal/shared/lpa.go
lambda/update/register.go
lambda/update/register_test.go
lambda/update/statutory_waiting_period.go
lambda/update/statutory_waiting_period_test.go
lambda/update/validate.go

Changes 'Perfect' status to 'Statutory Waiting Period'
Fixes VEGA-2586 
#patch

VEGA-2586 change perfect to statutory waiting period

---

lambda/update/attorney_opt_out.go
lambda/update/attorney_opt_out_test.go

Fixes [MLPAB-2318](https://opgtransform.atlassian.net/browse/MLPAB-2318).
[MLPAB-2318]: https://opgtransform.atlassian.net/browse/MLPAB-2318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MLPAB-2318: Stop updating LPA status on attorney opt out

---

docs/example-lpa.json
docs/schemas/2024-10/donor-details.json
internal/shared/lpa.go
internal/shared/lpa_test.go
lambda/create/main_test.go
lambda/create/validate.go
lambda/create/validate_test.go

I will uncomment things once I merge https://github.com/ministryofjustice/opg-modernising-lpa/pull/1535 to send them

MLPAB-2471 Add witnessed at times for lpa

---

fixtures/Dockerfile
fixtures/app.py
fixtures/requirements.txt
fixtures/static/js/json-schema-editor.mjs
fixtures/static/js/main.mjs
fixtures/static/js/uid-generator.mjs
fixtures/templates/index.html
lambda/Dockerfile
mock-apigw/Dockerfile
sonar-project.properties
terraform/environment/region/fixtures.tf
terraform/modules/fixtures_service/ecs.tf
terraform/modules/fixtures_service/load_balancer.tf
terraform/modules/fixtures_service/load_balancer_security.tf
terraform/modules/fixtures_service/security_group.tf
terraform/modules/fixtures_service/variables.tf

Fix [issues](https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&id=ministryofjustice_opg-data-lpa-store) and [security hotspots](https://sonarcloud.io/project/security_hotspots?id=ministryofjustice_opg-data-lpa-store) reported by SonarCloud
#patch
Dockerfiles and Terraform:
- Run containers as non-root user
- Use port 8080 for fixtures container (non-root users can't use port 80)
Python:
- Add CSRF protection
- Split safe and unsafe routes
- Don't run in debug mode
JavaScript:
- Don't use asynchronous constructor side-effects
- Add integrity check to external resources
I really liked how SonarCloud laid out [the cause of this security issue](https://sonarcloud.io/project/issues?impactSoftwareQualities=SECURITY&issueStatuses=OPEN%2CCONFIRMED&id=ministryofjustice_opg-data-lp …

Fix various issues reported by SonarCloud

---

internal/shared/person.go
lambda/create/validate.go
lambda/create/validate_test.go

Uses appointmentType to count attorneys
Fixes (VEGA-2656)

VEGA-2656 make appointment type required

---

terraform/account/terraform.tfvars.json

Fixes (Ticket Reference)
Explain how your code addresses the purpose of the change

UML-3808: allow ual to access jwt key

---

docs/example-lpa.json
docs/schemas/2024-10/donor-details.json
internal/shared/lpa.go
internal/shared/lpa_test.go
lambda/create/main_test.go

So we can record the language the LPA is being registered in

MLPAB-2420 Add language to Lpa

---

.github/workflows/account-deploy.yml
.github/workflows/env-deploy.yml
.github/workflows/env-destroy.yml
.pre-commit-config.yaml
terraform/account/.envrc
terraform/account/terraform.tf
terraform/environment/.envrc
terraform/environment/.terraform.lock.hcl
terraform/environment/terraform.tf
terraform/environment/terraform.tfvars.json

Use a LPA is unable to post a request to the lpa store.
Fixes UML-3816
- don't allow commits to main
- upgrade terraform
- fix assume role for backend config
- allow api task role to execute api

UML-3816 Fix ual access

---

internal/shared/jwt.go
internal/shared/jwt_test.go

Allows access via configured JWT issuer fields to the use project.
Fixes UML-3783

Add use Issuer to allowed list and create additional matching tests

---

.github/workflows/account-deploy.yml
.github/workflows/env-deploy.yml
.github/workflows/env-destroy.yml

Use a versioned composite action for setting terraform version in github actions
- use composite actions for parsing terraform version
- https://github.com/ministryofjustice/opg-github-actions/blob/main/.github/actions/terraform-version/README.md

use composite action for terraform version setting

---

docs/schemas/2024-10/donor-details-partial.json
fixtures/static/js/fetch-schema.mjs
fixtures/static/js/json-schema-editor.mjs

Fix the primary issue with the fixtures page (JS crashes and it doesn't load the editor), plus some other things
Fixes VEGA-2879 #patch
- Specify that `independentWitness` is an object
- Add `appointmentType` to attorneys
- Fetch embedded schemas from local server
- Fetch and merge remote ref schemas manually
- This isn't a very good solution, but it will work for now. And this is page is not designed for production use and already full of temporary solutions

Fix a few issues with the fixtures form

---

lambda/update/statutory_waiting_period.go
lambda/update/statutory_waiting_period_test.go

Fixes #311, where I used the wrong status
Fixes VEGA-2896 #minor

Do not require signatures from removed attorneys

---

internal/shared/attorneys.go
internal/shared/attorneys_test.go
lambda/create/set_defaults.go
lambda/create/validate.go
lambda/create/validate_test.go
lambda/update/correction.go
lambda/update/correction_test.go
lambda/update/parse/changes.go
lambda/update/parse/changes_test.go

https://opgtransform.atlassian.net/browse/MLPAB-2895

Add corrections for decisions

---

.github/workflows/account-deploy.yml
.github/workflows/build-push-images.yml
.github/workflows/codeql.yml
.github/workflows/env-deploy.yml
.github/workflows/env-destroy.yml
.github/workflows/env-test.yml
.github/workflows/generate-tag.yml
.github/workflows/go-test.yml
.github/workflows/pact-provider-verification.yml
.github/workflows/validate-api.yaml
.github/workflows/workflow-pr.yml
renovate.json

Use specific semvar tags for gh actions and turn on renovate digest pinning
Fix a vulnerability vector of actions being hijacked and semvar tags being pointed to compromised commit

SP-2699 - Pin GH actions to digests #minor

---

api_test.go
docs/example-lpa-all-paper.json
docs/paper-certificate-provider-access-online.json
lambda/update/paper_certificate_provider_access_online.go
lambda/update/paper_certificate_provider_access_online_test.go
lambda/update/validate.go

Enables [MLPAB-2876](https://opgtransform.atlassian.net/browse/MLPAB-2876)
[MLPAB-1550]: https://opgtransform.atlassian.net/browse/MLPAB-1550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MLPAB-2876]: https://opgtransform.atlassian.net/browse/MLPAB-2876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MLPAB-2876: Handle PAPER_CERTIFICATE_PROVIDER_ACCESS_ONLINE updates

---

terraform/environment/data_sources.tf
terraform/environment/eventbridge.tf
terraform/environment/iam_roles.tf
terraform/environment/metric_events.tf

Forward metric events to opg-metrics service
Fixes MLPAB-2980
- Create eventbridge rule to forward metric events to the API Destination
- Add IAM role for API destination invocation

MLPBA-2980 - create eventbridge rule for metrics

---

.github/workflows/schedule-update-opg-metrics-credentials.yml

Update API keys job failed due to incorrect inputs being used
Fixes MLPAB-3015
- replace underscores in input names

MLPAB-3015 - replace accidental underscores

---

terraform/environment/region/apigateway.tf
terraform/environment/region/data_sources.tf
terraform/environment/region/lambda.tf
terraform/environment/region/variables.tf
terraform/environment/regions.tf

Briefly describe the purpose of the change, and/or link to the JIRA ticket for context
Fixes (Ticket Reference)
Explain how your code addresses the purpose of the change

SP-2802 - Add IP Allow List to API Gateway #minor

---

lambda/create/main.go
lambda/create/main_test.go
lambda/update/main.go
lambda/update/main_test.go

MLPAB-2916 Split metrics by channel
